---
- name: download source of frr
  git:
    repo: "https://github.com/FRRouting/frr.git"
    dest: "{{ frr.location }}"
    version: stable/5.0
 
- name: Build FRR
  become: true
  block:
    - name: Add frr groups and user
      shell: |
        sudo groupadd -r -g 92 frr
        sudo groupadd -r -g 85 frrvty
        sudo adduser --system --ingroup frr --home /var/run/frr/ --gecos "FRR suite" --shell /sbin/nologin frr
        sudo usermod -a -G frrvty frr

    - name: Run bootstrap.sh
      shell: ./bootstrap.sh
      args:
        chdir: "/home/{{ frr.user }}/frr" 

    - name: Run configure file
      shell: ./configure --prefix=/usr --enable-exampledir=/usr/share/doc/frr/examples/  --localstatedir=/var/run/frr --sbindir=/usr/lib/frr  --sysconfdir=/etc/frr --enable-pimd --enable-watchfrr --enable-ospfclient=yes --enable-ospfapi=yes --enable-multipath=64 --enable-user=frr --enable-group=frr --enable-vty-group=frrvty --enable-configfile-mask=0640 --enable-logfile-mask=0640 --enable-rtadv --enable-fpm --enable-systemd=yes  --with-pkg-git-version
      args:
        chdir: "/home/{{ frr.user }}/frr" 

    - name: make
      make:
        chdir: "/home/{{ frr.user }}/frr" 

    - name: make check
      make:
        chdir: "/home/{{ frr.user }}/frr" 
        target: check
       
    - name: make install
      make:
        chdir: "/home/{{ frr.user }}/frr" 
        target: install

    - name: Create empty FRR configuration files
      shell: |
        install -m 755 -o frr -g frr -d /var/log/frr
        install -m 775 -o frr -g frrvty -d /etc/frr
        install -m 640 -o frr -g frr /dev/null /etc/frr/zebra.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/bgpd.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/ospfd.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/ospf6d.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/isisd.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/ripd.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/ripngd.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/pimd.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/ldpd.conf
        install -m 640 -o frr -g frr /dev/null /etc/frr/nhrpd.conf
        install -m 640 -o frr -g frrvty /dev/null /etc/frr/vtysh.conf

    - name: Enable IPv4 forwarding
      replace:
        path: /etc/sysctl.conf
        regexp: '#net.ipv4.ip_forward=1'
        replace: 'net.ipv4.ip_forward=1'

    - name: Enable IPv6 forwarding
      replace:
        path: /etc/sysctl.conf
        regexp: '#net.ipv6.conf.all.forwarding=1'
        replace: 'net.ipv6.conf.all.forwarding=1'

    - name: Apply the changes 
      shell: sysctl -p

    - name: Install the systemd service
      shell: |
        install -m 644 "/home/{{ frr.user }}/frr/tools/frr.service" /etc/systemd/system/frr.service
        install -m 644 "/home/{{ frr.user }}/frr/tools/etc/default/frr" /etc/default/frr
        install -m 644 "/home/{{ frr.user }}/frr/tools/etc/frr/daemons" /etc/frr/daemons
        install -m 644 "/home/{{ frr.user }}/frr/tools/etc/frr/daemons.conf" /etc/frr/daemons.conf
        install -m 644 "/home/{{ frr.user }}/frr/tools/etc/frr/frr.conf" /etc/frr/frr.conf
        install -m 644  -o frr -g frr "/home/{{ frr.user }}/frr/tools/etc/frr/vtysh.conf" /etc/frr/vtysh.conf

    - name: Enable daemons
      replace:
        path: /etc/frr/daemons
        regexp: 'zebra=no'
        replace: 'zebra=yes'

      notify:
        - frr
